description: Link to wiki/productstoavoid
has_inline: true
message:
 - "For reasons to avoid any and all driver updater software, CCleaner, µTorrent, BitComet, BitLord, BitTorrent, Any and ALL Free VPNs, Brave, Opera, Kaspersky, Avast, Norton, Ubuntu/Ubuntu derivatives, Vivaldi, Windows 7, see "
 - text: this Wiki entry
   link: https://old.reddit.com/r/24hoursupport/wiki/productstoavoid
