description: Link to wiki/productstoavoid
has_inline: true
message:
 - "For reasons to avoid any and all driver updater software, CCleaner, µTorrent, BitComet, BitLord, BitTorrent, Any and ALL Free VPNs, Brave, Opera, Kaspersky, Avast, Norton, Ubuntu/Ubuntu derivatives, Vivaldi, Windows 7, see "
 - text: this Wiki entry
   link: https://github.com/24HourSupport/Wiki/blob/main/productstoavoid.md
 - |-
    .
    
    Please read wiki by clicking the above hyperlink (blue text) before asking **"What is this?"** or **"Is this safe?"**
    
noinline_add: |-
    https://cdn.discordapp.com/attachments/514431063221731338/788540526059585586/2Q.png
